### ISSUE TITLE
Do you know about issue templates?

### ISSUE THREAD

**Issue by curtisblackwell** [alexyingchen/accessguide#1]
Using an [issue template](https://github.blog/2016-02-17-issue-and-pull-request-templates) would probably increase the chances that people reference the number as you requested and just provide more structure to help guide issue-loggers to leaving more helpful info.

I'm happy to help you make one if you're interested. As an example, here's one I have from a side project:

```md
<!--
  Add a story phrase matching the pattern: "As a _, I expect _ so _." E.g. *As a player, I expect I can roll dice so I can determine how many spaces I can move.*

  Give scenarios general, descriptive names. E.g. *Saving a game* or *Continuing a saved game*.
-->

storyPhrase

## Scenarios
### scenarioName
I expect:

- [ ] something
- [ ] another thing
```

…now off to actually contribute what you requested.

**Comment by thetuttingtutor** [comment]
This is cool, @curtisblackwell! I will hold off on this for now since we're going to use this repo for the web development too so that might change what types of issues people log, but I'll make the suggestion.
