### ISSUE TITLE
Programmer’s Guide TOC/top-level section wording could use improvement

### ISSUE THREAD

**Issue by Noleli** [alexyingchen/accessguide#10]
Most top-level section headers in the Programmer’s Guide are nouns, which is good. There are two exceptions:

**Programmatically determined** is functioning as an adjective, and it makes it awkward. Programmatically determined *what*‽‽ Maybe “Programmatic control” or “Machine readability”? Unless PD is a standard term, as suggested in #7.

**Bypass content** is — I think — an imperative here. It’s made extra confusing because “bypass” can be either noun or a verb. Maybe “Bypassable content”? Or more simply, “Skippable content”?

**Comment by thetuttingtutor** [comment]
Very belated response!

I have received very similar feedback that **programmatically determined** is confusing, therefore I have changed it to **defined in markup**, e.g. "Make the human language defined in markup." Thoughts on the word change?

I like the suggestion for **Skippable content**, I'll keep that in mind for the next wording update I do.

**Comment by Noleli** [comment]
“Defined in markup” is definitely an improvement. It doesn’t say what is being defined in the markup, though. “Semantic markup” is a pretty commonly understood concept, so you could just call it that.

If you want to keep it more general, Wikipedia describes the general concept as “[Separation of content and presentation](https://en.wikipedia.org/wiki/Separation_of_content_and_presentation)”, which could also be a good (if long) section header.
