### ISSUE TITLE
Px: Code samples formatted inconsistently

### ISSUE THREAD

**Issue by curtisblackwell** [alexyingchen/accessguide#2]
- Most code samples are indented with tabs, some with spaces.
- Matching opening/closing tags often aren't indented to the same level.
- There are curly quotes throughout.
- Sometimes the attributes have spaces around the `=`.
- Some text is English while most is Latin. (I'd like to see more realistic text, b/c I find it more engaging.)
- Rather than use "©" I'd use the HTML entity `&copy;`. (P1)

**Comment by thetuttingtutor** [comment]
@MichellanneLi can you take a look at the formatting issues that Curtis mentioned?

@curtisblackwell I'm planning to go back in and re-write some of the content in English so that will get rid of the filler copy.
