### ISSUE TITLE
P9: Partially unclear

### ISSUE THREAD

**Issue by curtisblackwell** [alexyingchen/accessguide#4]
> Ensure all the functionality is operable through a keyboard interface without requiring specific timing for keystrokes (except where input is defined by the user’s movement and not just the endpoints). To be more advanced, there are no exceptions.

I don't understand anything from the parentheses to the end.

**Comment by thetuttingtutor** [comment]
TBH I didn't fully understand this either. I took "where input is defined by the user's movement and not just the endpoints" directly from [WCAG 2.1.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-keyboard-operable.html) - will ask an industry expert for clarification.
