### ISSUE TITLE
Typos and the like

### ISSUE THREAD

**Issue by curtisblackwell** [alexyingchen/accessguide#6]
## P7
"then I don’t know of the form" should be "then I don’t know *if* the form"

## P13
> Avoid making content appear and disappear on focus or hover, since this is disorienting. If hover or focus does make additional content visible and then hidden, the following are true:

"the following are true:" would probably be clearer as "follow these guidelines"

## P16
The events are called the mousedown event and the mouseup event.

## P18
"I get really disoriented and takes me awhile" should be "I get really disoriented and it takes me a while"

---

Note to self: I stopped on P18.

**Comment by thetuttingtutor** [comment]
Thanks for catching these!
