### ISSUE TITLE
Introduction: new section? (basics of accessibility mechanics)

### ISSUE THREAD

**Issue by waillama** [alexyingchen/accessguide#9]
On my first pass through the programmer's guide, I didn’t have a good sense of how these suggestions tied into the user experience because I was unfamiliar with how assistive technologies work. I found the guide more helpful after watching a few videos which illustrated issues that can come up with keyboard-only navigation and screen readers. For example, they described how screen readers interpret HTML elements, how they travel through the DOM, and how they communicate a page’s structure and content to the user. That context helped make the suggestions more concrete on my next time through.

- Leonie Watson - Developer's Guide to Accessibility Mechanics: https://www.youtube.com/watch?v=qi0tY60Hd6M

- Making Accessible Web Apps Using HTML5 and ChromeVox: https://www.youtube.com/watch?v=x18vEEfpK3g

- How A Blind Developer Uses Visual Studio: https://www.youtube.com/watch?v=94swlF55tVc

**Comment by thetuttingtutor** [comment]
We'll have an assistive tech section in the glossary - perhaps we can also include links to these videos/demos
